# JEmoji by JoseMarcellio
# set permission to "none" to bypass emoji permission
# bypass global permission "jemoji.*"
# custom head support! head;texture
# hex support for 1.16+
# placeholderapi support for gui name, name, and lore!
# set permission to "none" or change price to -1 to disable economy
# list executor:
# [success-close-inventory], [success-console-command], [success-message], [success-chat], [success-player-command], [success-sound]
# [failed-close-inventory], [failed-console-command], [failed-message] ,[failed-chat] ,[failed-player-command], [failed-sound]
# placeholder executor: {player}, {price}, {emoji}, and {permission}

gui-name: "&8JEmoji GUI"

clear-color-after-emoji: true
clear-color-symbol: "&r"

status-owned: "&cYou already have this emoji!"
status-purchase: "&eClick to purchase!"

emoji:
  "<3":
    name: "{emoji}"
    icon: "EMERALD"
    set-emoji: "&c❤"
    permission: "jemoji.<3"
    price: 250
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
      - " "
      - "{status}"
    executor:
      - "[success-console-command]lp user {player} permission set {permission}"
      - "[success-sound]NOTE_PLING"
      - "[success-message]&7You purchased {emoji} &7for &a{price}"
      - "[success-close-inventory]"
      - "[failed-sound]ENDERMAN_TELEPORT"
      - "[failed-message]&7You need &a{price} &7to purchase {emoji}"
      - "[failed-close-inventory]"
    disable-world: []
  ":cat:":
    name: "{emoji}"
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWY3YjA1NWU2ZmVmOTE0ZGNkMmI4NjJhZGMwMWI4MzM4ZTc5ZTFiMjZhYzNhNzExZjg4ZDE2NzZjNDI4NjgxNSJ9fX0="
    set-emoji: "&e= &b＾● ⋏ ●＾ &e="
    permission: "jemoji.cat"
    price: 500
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
      - " "
      - "{status}"
    executor:
      - "[success-console-command]lp user {player} permission set {permission}"
      - "[success-sound]NOTE_PLING"
      - "[success-message]&7You purchased {emoji} &7for &a{price}"
      - "[success-close-inventory]"
      - "[failed-sound]ENDERMAN_TELEPORT"
      - "[failed-message]&7You need &a{price} &7to purchase {emoji}"
      - "[failed-close-inventory]"
    disable-world: []
  ":yey:":
    name: "{emoji}"
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTJlOTgxNjVkZWVmNGVkNjIxOTUzOTIxYzFlZjgxN2RjNjM4YWY3MWMxOTM0YTQyODdiNjlkN2EzMWY2YjgifX19"
    set-emoji: "&aヽ (◕◡◕) ﾉ"
    permission: "jemoji.yey"
    price: 500
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
      - " "
      - "{status}"
    executor:
      - "[success-console-command]lp user {player} permission set {permission}"
      - "[success-sound]NOTE_PLING"
      - "[success-message]&7You purchased {emoji} &7for &a{price}"
      - "[success-close-inventory]"
      - "[failed-sound]ENDERMAN_TELEPORT"
      - "[failed-message]&7You need &a{price} &7to purchase {emoji}"
      - "[failed-close-inventory]"
    disable-world: []
  ":puffer:":
    name: "{emoji}"
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjkyMzUwYzlmMDk5M2VkNTRkYjJjNzExMzkzNjMyNTY4M2ZmYzIwMTA0YTliNjIyYWE0NTdkMzdlNzA4ZDkzMSJ9fX0="
    set-emoji: "&e<('O')>"
    permission: "jemoji.puffer"
    price: 1000
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
      - " "
      - "{status}"
    executor:
      - "[success-console-command]lp user {player} permission set {permission}"
      - "[success-sound]NOTE_PLING"
      - "[success-message]&7You purchased {emoji} &7for &a{price}"
      - "[success-close-inventory]"
      - "[failed-sound]ENDERMAN_TELEPORT"
      - "[failed-message]&7You need &a{price} &7to purchase {emoji}"
      - "[failed-close-inventory]"
    disable-world: []
  ":dog:":
    name: "{emoji}"
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjkzZDFiYzQwNWQ5ZGU2MDA4ZWNjYjI1MzkxZWQ4ZWY4MDllZDViNWRmZmJkMTBjNjQ5YmM4YTQ4YjZlOTFlIn19fQ=="
    set-emoji: "&6(ᵔᴥᵔ)"
    permission: "jemoji.dog"
    price: 1000
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
      - " "
      - "{status}"
    executor:
      - "[success-console-command]lp user {player} permission set {permission}"
      - "[success-sound]NOTE_PLING"
      - "[success-message]&7You purchased {emoji} &7for &a{price}"
      - "[success-close-inventory]"
      - "[failed-sound]ENDERMAN_TELEPORT"
      - "[failed-message]&7You need &a{price} &7to purchase {emoji}"
      - "[failed-close-inventory]"
    disable-world: []
